#!/bin/bash

trap "clear && exit 0" INT

HEIGHT=100
WIDTH=70
CHOICE_HEIGHT=100
BACKTITLE="Press Ctrl+c to quit"

browse() {

    MENU="$PWD:"
    TITLE="Choose a file to open in Sublime"

    ALL=(*)

    DIRS=(">search" "" "<back" "")
    FILES=()

    for ((i = 0; i < ${#ALL[@]}; i++))
    do
        if [ -d ${ALL[$i]} ]; then
            DIRS+=("${ALL[$i]}/")
            DIRS+=("")
        else
            FILES+=("${ALL[$i]}")
            FILES+=("")
        fi
    done

    OPTIONS=("${DIRS[@]}" "${FILES[@]}")

    CHOICE=$(dialog --clear \
                    --backtitle "$BACKTITLE" \
                    --ok-label "Select" \
                    --no-cancel \
                    --title "$TITLE" \
                    --menu "$MENU" \
                    $HEIGHT $WIDTH $CHOICE_HEIGHT \
                    "${OPTIONS[@]}" \
                    2>&1 >/dev/tty)

    if [ $CHOICE == ">search" ]; then
        search
    elif [ $CHOICE == "<back" ]; then
        cd ..
        browse
    elif [ -d $CHOICE ]; then
        cd $CHOICE
        browse
    else
        rsub $CHOICE
        browse
    fi
}

setup() {

    if command -v rsub >/dev/null 2>&1; then

        if command -v dialog >/dev/null 2>&1; then

            browse
        else
            echo "dialog not found. Installing it..."

            sudo yum install dialog

            if command -v dialog >/dev/null 2>&1; then

                browse
            else
                echo "Installing dialog failed."

                exit 1
            fi
        fi

    else
        echo "rsub not found. Installing it..."

        sudo wget -O /usr/local/bin/rsub https://raw.github.com/aurora/rmate/master/rmate

        sudo chmod 777 /usr/local/bin/rsub

        if command -v rsub >/dev/null 2>&1; then
            setup
        else
            echo "Installing rsub failed."

            exit 1
        fi
    fi
}

search() {

    MENU="Search file and directory names"
    TITLE="Search:"

    SEARCH=$(dialog --clear \
                    --backtitle "$BACKTITLE" \
                    --ok-label "Search" \
                    --no-cancel \
                    --title "$TITLE" \
                    --inputbox "$MENU" \
                    $HEIGHT $WIDTH \
                    2>&1 >/dev/tty)

    DIRS=("<back" "")
    FILES=()

    RESULTS=($(find . -regex ".*$SEARCH.*"))
    
    for ((i = 0; i < ${#RESULTS[@]}; i++))
    do
        if [ -d ${RESULTS[$i]} ]; then
            DIRS+=("${RESULTS[$i]}/")
            DIRS+=("")
        else
            FILES+=("${RESULTS[$i]}")
            FILES+=("")
        fi
    done

    OPTIONS=("${DIRS[@]}" "${FILES[@]}")

    MENU="Results:"
    TITLE="Choose a file to open in Sublime"

    CHOICE=$(dialog --clear \
                    --backtitle "$BACKTITLE" \
                    --ok-label "Select" \
                    --no-cancel \
                    --title "$TITLE" \
                    --menu "$MENU" \
                    $HEIGHT $WIDTH $CHOICE_HEIGHT \
                    "${OPTIONS[@]}" \
                    2>&1 >/dev/tty)
    
    if [ $CHOICE == "<back" ]; then
        browse
    else
        rsub $CHOICE
        browse
    fi
}

setup
